services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_lab
    environment:
      POSTGRES_DB: dbspark_lab
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./исходные_данные:/data/csv:ro
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dbspark_lab"]
      interval: 5s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:24.3-alpine
    container_name: clickhouse_lab
    environment:
      CLICKHOUSE_DB: lab_reports
      CLICKHOUSE_USER: lab_user
      CLICKHOUSE_PASSWORD: lab_pass
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --user lab_user --password lab_pass -q 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7.0
    container_name: mongodb_lab
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ ping: 1 })'"]
      interval: 5s
      timeout: 5s
      retries: 5

  spark:
    image: eclipse-temurin:11-jre-focal
    container_name: spark_lab
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./code:/code
      - ./исходные_данные:/data/csv
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    command: >
      bash -c "
      export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin &&
      apt-get update && 
      apt-get install -y python3 python3-pip wget && 
      wget -q https://archive.apache.org/dist/spark/spark-3.3.2/spark-3.3.2-bin-hadoop3.tgz && 
      tar -xzf spark-3.3.2-bin-hadoop3.tgz && 
      mv spark-3.3.2-bin-hadoop3 /opt/spark && 
      rm spark-3.3.2-bin-hadoop3.tgz && 
      pip3 install pyspark psycopg2-binary 'clickhouse-connect<0.8.0' pandas requests && 
      echo 'Waiting for PostgreSQL to fully initialize...' &&
      sleep 10 &&
      echo 'Starting ETL process...' &&
      python3 /code/etl_reports_clickhouse.py &&
      echo 'ETL completed successfully!' &&
      tail -f /dev/null
      "

volumes:
  postgres_data:
  clickhouse_data:
  mongodb_data: